### ISSUE TITLE
Package evaluation & first pass documentation

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/epidatpy#9]
The goal of this task is to better understand whether this package does what we need it to, and permit other Delphi members to understand the same without having to read the source.

Delphi blog posts that include plots also include the code used to produce those plots. Reproduce as many of the plots as you can from the following blog posts, using this package instead of `covidcast`. 

* [Home for the Holidays: surveys indicators](https://delphi.cmu.edu/blog/2021/02/02/home-for-the-holidays-the-impact-of-us-holidays-on-social-behaviors-and-preventative-measures/)
* [Syndromic outpatient indicator from claims](https://delphi.cmu.edu/blog/2020/11/05/a-syndromic-covid-19-indicator-based-on-insurance-claims-of-outpatient-visits/) 

Use your newly acquired knowledge to flesh out [the package documentation](https://github.com/cmu-delphi/delphi-epidata-py/tree/dev/docs) with the basics.

**Comment by lee14257** [comment]
#10 This is the PR for initial documentation and guide for the package

**Comment by dshemetov** [comment]
TODO:

- [ ] add documentation (there's barely any)
  - [ ] get documentation buildable
  - [ ] sign up for hosting on readthedocs.org
  - [ ] port R vignettes and examples over
- [ ] add tests
- [ ] make sure the endpoint interfaces are the same 
  - [x] rename endpoints to pub_ when needed
  - [x] double check that argument order is the same
  - [x] add support for `geo_value = "*"` default on most endpoints
  - [ ] add a fetch_args_list component
  - [ ] add caching
- [ ] make sure the parameter validation for each endpoint either matches R or is of good quality for Python
  - [ ] make sure date inputs to all endpoints can be string, date, or int (needs a utility)
- [ ] make sure that the data type casting from the API's JSON response to Pandas works well
- [ ] get rid of all the unnecessary non-Pandas return options and just return a df by default
- [ ] get rid of the overhead around non-Pandas types (like csv and classic and json and jsonl)

**Comment by dshemetov** [comment]
@rzats Here is a task you can work on. Feel free to ping me here or on Slack if something is unclear! TL;DR: we need to build a basic query test file.

> port R vignettes and examples over
So some of the examples we want to port are in docstrings in the R functions. [Here](https://github.com/cmu-delphi/epidatr/blob/626c30bc07f4aae3c3e6a6c6b825a6cd5eee1ce7/R/endpoints.R#L7-L13) is an example for `pvt_cdc` endpoint (the endpoints marked with `pvt_` are private and require a special key to access (different from the rate-limited API key); ask Brian for those). So what we would look like is to take those queries and port those to this package. At this point, let's just do it in a test file like `test_epidata_calls.py`, since I'm not sure if Python supports those kinds of examples in docstrings. Each test should make an equivalent call with the Python client and make sure that the output is non-trivial (as in non-empty; if some of them come back empty, then talk to me, and we should fix the query).

I expect that there may be errors along the way when trying to reproduce these (for various reasons, like function input data types or parsing issues, etc.). Record those as TODO items here.

**Comment by dshemetov** [comment]
Initial package evaluation and first pass documentation Done. Moving bigger picture items to #11
